basePath: /api/v1
definitions:
  handler.Response:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  handler.errorResponse:
    properties:
      error:
        type: string
      status:
        type: integer
    type: object
  models.Account:
    properties:
      created-at:
        type: string
      id:
        type: integer
      profile_image:
        type: string
      user_id:
        type: integer
    type: object
  models.CreatePostRequest:
    properties:
      categories:
        items:
          type: integer
        type: array
      description:
        type: string
      images:
        items:
          type: string
        type: array
      title:
        type: string
    required:
    - images
    - title
    type: object
  models.GetAllUserPostsResponse:
    properties:
      user_posts:
        items:
          $ref: '#/definitions/models.GetPostByIdResponse'
        type: array
    type: object
  models.GetAllUsersPosts:
    properties:
      categories:
        items:
          type: string
        type: array
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      images:
        items:
          type: string
        type: array
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
      username:
        type: string
    required:
    - title
    - user_id
    - username
    type: object
  models.GetAllUsersPostsRequest:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      sorting:
        type: string
    type: object
  models.GetPostByIdResponse:
    properties:
      categories:
        items:
          type: integer
        type: array
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      images:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  models.SignInRequest:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  models.SignInResponse:
    properties:
      token:
        type: string
    type: object
  models.SignUpRequest:
    properties:
      login:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - login
    - password
    - username
    type: object
  models.SignUpResponse:
    properties:
      account_id:
        type: integer
      user_id:
        type: integer
    type: object
  models.UpdateAccountRequest:
    properties:
      profile_image:
        type: string
      user_id:
        type: integer
    type: object
  models.UpdateUserResponse:
    properties:
      id:
        type: integer
      login:
        type: string
      password:
        type: string
      role_id:
        type: integer
      username:
        type: string
    required:
    - id
    type: object
  models.User:
    properties:
      created_at:
        type: string
      id:
        type: integer
      login:
        type: string
      password:
        type: string
      role_id:
        type: integer
      username:
        type: string
    required:
    - login
    - password
    - username
    type: object
host: localhost:8000
info:
  contact:
    email: mirchenko1702@gmail.com
    name: API Support
  description: Swagger API for Designers App
  termsOfService: http://swagger.io/terms/
  title: Designers App Swagger API
  version: "1.0"
paths:
  /account/:id:
    get:
      consumes:
      - application/json
      description: get account info by user id
      operationId: get-account
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Get account info
      tags:
      - account
    put:
      consumes:
      - application/json
      description: update user account data
      operationId: update-account
      parameters:
      - description: account update info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.UpdateAccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Update account by user id
      tags:
      - account
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login
      operationId: login
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success login
          schema:
            $ref: '#/definitions/models.SignInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: SignIn
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-user
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SignUpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: SignUp
      tags:
      - auth
  /posts/:
    post:
      consumes:
      - application/json
      description: create post with account id that written in context
      operationId: delete-post
      parameters:
      - description: post info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.CreatePostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Create post
      tags:
      - posts
  /posts/:id:
    delete:
      consumes:
      - application/json
      description: delete post by post id
      operationId: create-post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Delete post
      tags:
      - posts
    get:
      consumes:
      - application/json
      description: Get post by post id
      operationId: get-post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetPostByIdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Get post
      tags:
      - posts
  /posts/users/:
    get:
      description: Get all users posts
      operationId: get-users-posts
      parameters:
      - description: params for partition
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.GetAllUsersPostsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.GetAllUsersPosts'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Get all users posts
      tags:
      - posts
  /posts/users/:id:
    get:
      consumes:
      - application/json
      description: Get all user post by user id
      operationId: get-user-posts
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetAllUserPostsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Get user posts
      tags:
      - posts
  /users/:
    get:
      consumes:
      - application/json
      description: get all users
      operationId: get-all-users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Get all users
      tags:
      - user
    put:
      consumes:
      - application/json
      description: Update user fields
      operationId: update-user
      parameters:
      - description: user fields to update
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.UpdateUserResponse'
      produces:
      - application/json
      responses:
        "200":
          description: message
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Update User fields
      tags:
      - user
  /users/:id:
    delete:
      consumes:
      - application/json
      description: delete user by id
      operationId: delete-user-by-id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: message
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Delete User By Id
      tags:
      - user
    get:
      consumes:
      - application/json
      description: get user by id
      operationId: get-user-by-id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Get User By Id
      tags:
      - user
swagger: "2.0"
